- DESCRIPTION
- R/model_performance.bayesian.R
- R/r2_bayes.R
- tests/testthat/test-model_performance.bayesian.R
Minor R2 bayes adjustements for condsistency and usage by report
- store all point estimates for R2_bayes
- pass on attributes to model_performance
- Change name of r2_loo_adjusted to r2_adjusted to follow consistency of SE etc.
- still think SE should be renamed to match what is actually computed (SD or MAD)
> R2 bayes changes

- DESCRIPTION
- R/r2.R
`gamlss` inherits from `gam`, and `summary.gamlss` automatically prints out a summary to the console when called. This captures the printout to ensure that `model_performance` is silent when assigned.
```{r}
library(gamlss)
library(performance)
dat <- rgamma(100, shape=1, scale=10)
mod <- gamlss(dat ~ 1, family = GA, trace = FALSE)
x <- model_performance(mod)
```
> suppress printout in model_performance.gamlss

- R/model_performance_default.R
Also, in the interest of code maintainability, it might be nice to transition to using `sprintf()` instead of `paste0()` for compositing strings.
For example, here:
`sprintf("Objects of class '%1$s' are not supported model objects.", class(model)[1])`
The nice thing here is that you don't have to manage the commas and quotes to start and stop the various pieces of the string, you can just refer to the with the `%<character>` structures as stand-ins (similar to glue without named arguments). The `$<number>` bit can be used to explicitly refer to supplied values by position instead of implicitly by order.
> Fix typo in warning; refer to 'supported' not 'valid'

- R/check_homogeneity.R
To my understanding, using Bartlett's test, you can't conclude that the variances are the same in absolute terms, you can only say there is insufficient evidence to claim otherwise. https://www.statology.org/bartletts-test/
Perhaps there is a better way to express this in the function output, but I think it's important not to mislead people who will be casually using the test without fully understanding its methodology.
> Updating conclusion if alpha > 0.05.

- R/compare_performance.R
- R/looic.R
- R/model_performance.bayesian.R
- man/compare_performance.Rd
- tests/testthat/test-compare_performance.R
This adds model comparison/stacking weights based on information criteria to the `compare_performance()` function
Closes https://github.com/easystats/performance/issues/255
> Add IC weights compare_performance function.

- R/check_zeroinflation.R
Closes https://github.com/easystats/performance/issues/367
Co-Authored-By: Claudio Zandonella Callegher <44664104+ClaudioZandonella@users.noreply.github.com>
> Fix check_zeroinflation for glmmTMB models

- R/check_model_diagnostics.R
- R/performance_cv.R
- R/performance_mae.R
- R/r2.R
When we don't need confidence intervals, it is much faster to skip their computation.
> ci=NULL speeds up computation

- R/check_model.R
Hi @strengejacke and other members of easystats,
Big fan of your tools here :)
I've just noticed a small typo in the warning when `see` is not installed.
> Fix typos in warning

- R/check_outliers.R
This PR removes a typo where an extra backtick was added which messed up the styling in documentation.
> fix: rm additional backticks messing with styling

- NEWS.md
- R/check_outliers.R
Fixes #496 (`check_outliers` throws error when passing multiple element to threshold list)
---
``` r
devtools::load_all(".../forks/performance")
packageVersion("performance")
#> [1] '0.10.0.4'
check_outliers(mtcars, method = c(
"zscore", "mahalanobis"), threshold = list(
'zscore' = 2.5, 'mahalanobis' = 15))
#> 2 outliers detected: cases 9, 31.
#> - Based on the following methods and thresholds: zscore (2.5),
#>   mahalanobis (15).
#> - For variables: mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb.
#> Note: Outliers were classified as such by at least half of the selected methods. 
#> 
#> -----------------------------------------------------------------------------
#> The following observations were considered outliers for two or more variables 
#> by at least one of the selected …
```
> Fixes #496 (`check_outliers` throws error when passing multiple element to threshold list)

- R/check_outliers.R
- tests/testthat/test-check_outliers.R
In this PR, I've fixed some (commented out) tests that were failing. One of the reasons they were failing was that I needed to also apply the fix from #497 to model-based outliers (to support user-specified thresholds). Once that was done, the tests were working.
> Add tests, fix bug with model-based outliers and multiple thresholds

- R/helpers.R
- R/performance_aicc.R
In some models, `get_loglikelihood()` does not work, but `stats::AIC` and `stats::BIC` can still return useable results. For example, fixest:
```r
library(fixest)
mod <- feols(mpg ~ hp, data = mtcars)
stats::AIC(mod)
stats::BIC(mod)
```
> AIC and BIC without loglikelihood

- R/item_intercor.R
- man/item_intercor.Rd
> Minor bug: Default method in item_intercor() is 'pearson', not 'spearman'

- R/looic.R
- R/model_performance.bayesian.R
- R/model_performance.rma.R
- R/r2_bayes.R
- man/looic.Rd
- man/model_performance.rma.Rd
- man/model_performance.stanreg.Rd
- man/r2_bayes.Rd
Ref:
- https://github.com/easystats/easystats/issues/343
- https://github.com/easystats/easystats/issues/318
> try to reduce warnings in examples and use examplesIf

- R/logLik.R
- tests/testthat/test-logLik.R
> Recursion in `logLik.plm()` that slows down computations:

- NEWS.md
- R/binned_residuals.R
- R/check_model.R
- R/check_outliers.R
- man/binned_residuals.Rd
- man/check_model.Rd
- man/check_outliers.Rd
- tests/testthat/test-binned_residuals.R
> Improve `binned_residuals()`

- DESCRIPTION
- NEWS.md
- R/binned_residuals.R
- R/check_model.R
- R/check_predictions.R
- R/looic.R
- R/r2_bayes.R
- man/binned_residuals.Rd
- man/looic.Rd
- man/r2_bayes.Rd
- tests/testthat/test-binned_residuals.R
- tests/testthat/test-check_predictions.R
> posterior predictive check for binomial glm with matrix response

- DESCRIPTION
- NEWS.md
- R/binned_residuals.R
- tests/testthat/test-binned_residuals.R
> Simple glms no longer supported?

- DESCRIPTION
- NEWS.md
- R/check_heterogeneity_bias.R
- R/check_model.R
- R/check_model_diagnostics.R
- R/check_outliers.R
- R/icc.R
- R/r2.R
- R/r2_bayes.R
- R/r2_coxsnell.R
- R/r2_loo.R
- R/test_bf.R
- R/test_likelihoodratio.R
- R/test_performance.R
- R/test_vuong.R
- R/test_wald.R
- man/check_outliers.Rd
- man/performance-package.Rd
- tests/testthat/test-check_outliers.R
- vignettes/check_outliers.Rmd
Fixes #672 
`percentage_central` now works. As discussed in #672
---
Reprex:
``` r
library(performance)
alpha <- 0.1
check_outliers(mtcars, method = "mcd", 
percentage_central = .50,
threshold = stats::qchisq(p = 1 - alpha, df = ncol(mtcars))) |>
which() |>
length()
#> [1] 15
check_outliers(mtcars, method = "mcd", 
percentage_central = .75,
threshold = stats::qchisq(p = 1 - alpha, df = ncol(mtcars))) |>
which() |>
length()
#> [1] 10
check_outliers(mtcars, method = "mcd", 
percentage_central = .25,
threshold = stats::qchisq(p = 1 - alpha, df = ncol(mtcars))) |>
which() |>
length()
#> Error in MASS::cov.rob(x, quantile.used = percentage_central * nrow(x), : 'quantile' must be at least 12
```
<sup>Created on 2024-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Fix problem with `percentage_central` argument in `check_outliers()` with MCD method

- DESCRIPTION
- NEWS.md
- R/check_collinearity.R
- R/check_model.R
- R/check_outliers.R
- man/check_outliers.Rd
- tests/testthat/test-check_collinearity.R
- tests/testthat/test-check_model.R
- tests/testthat/test-check_outliers.R
> difficult-to-diagnose errors using "difftime" response in a linear model

- DESCRIPTION
- NEWS.md
- R/check_singularity.R
- tests/testthat/test-check_singularity.R
> `check_singularity` doesn't work for `glmmTMB`

- DESCRIPTION
- NEWS.md
- R/check_htest.R
- inst/WORDLIST
- tests/testthat/test-check_homogeneity.R
- tests/testthat/test-check_normality.R
> Error checking normality for t.test

- DESCRIPTION
- R/helpers.R
- tests/testthat/test-helpers.R
- tests/testthat/test-r2_nagelkerke.R
> spurious(?) viewport-too-small error with new ggplot2 version 3.5.0

- vignettes/check_outliers.Rmd
> Update check_outliers.Rmd - remove references to JOSE

- DESCRIPTION
- NEWS.md
- R/check_homogeneity.R
- R/check_model.R
- R/check_predictions.R
- R/cronbachs_alpha.R
- inst/WORDLIST
- tests/testthat/test-check_model.R
- tests/testthat/test-cronbachs_alpha.R
> Check_model in version 0.11.0 no longer produces qq plot residuals

- .gitignore
- R/check_outliers.R
- man/check_outliers.Rd
Closes #711
---
``` r
library(see)
library(lme4)
library(performance)
set.seed(123)  # for reproducibility
n <- 100
subjectID <- paste("Subject", rep(1:10, each = 10))
PN <- runif(n, 0, 100)
alpha <- 0.5 * PN + rnorm(n, mean = 50, sd = 10)
alpha[c(20, 40)] <- c(150, 160)  # arbitrarily chosen subjects for outliers
data <- data.frame(subjectID, PN, alpha)
model <- lmer(alpha ~ PN + (1 | subjectID), data = data)
x <- check_outliers(model)
plot(x)
```
<sup>Created on 2024-04-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> Fixes bug in outlier plot method

- DESCRIPTION
- NEWS.md
- R/check_heterogeneity_bias.R
- R/performance_cv.R
- man/check_heterogeneity_bias.Rd
- tests/testthat/test-check_heterogeneity_bias.R
https://github.com/easystats/easystats/issues/404
> Rename `group`/`group_by` arguments into `by`

- DESCRIPTION
- tests/testthat/test-icc.R
- tests/testthat/test-model_performance.bayesian.R
- tests/testthat/test-model_performance.merMod.R
> Remove unnecessary `tryCatch()` statements targeting `insight::download_model()`

- DESCRIPTION
- R/check_predictions.R
- tests/testthat/test-check_model.R
> check_predictions() fails when outcome is log-transformed and named like a valid function

- DESCRIPTION
- NEWS.md
- R/check_predictions.R
- tests/testthat/test-check_predictions.R
> Possible bug: error is thrown saying check_model is not implemented, if model formula contains a ratio

- DESCRIPTION
- R/check_dag.R
- tests/testthat/_snaps/check_dag.md
- tests/testthat/test-check_dag.R
```r
dag <- check_dag(
podcast ~ mood + humor + skills_course,
alertness ~ mood,
mood ~ humor,
prepared ~ skills_course,
exam ~ alertness + prepared,
exposure = "podcast",
outcome = "exam",
coords = time_ordered_coords()
)
dag
dag <- check_dag(
podcast ~ mood + humor + skills_course,
alertness ~ mood,
mood ~ humor,
prepared ~ skills_course,
exam ~ alertness + prepared,
adjusted = c("alertness", "prepared"),
exposure = "podcast",
outcome = "exam",
coords = time_ordered_coords()
)
dag
```
> Fix issues with multiple possible adjustments

- DESCRIPTION
- R/check_dag.R
- man/check_dag.Rd
- tests/testthat/_snaps/check_dag.md
Currentyl, msg for direct and total effect are printed, even if adjustment sets are identica.l This PR aims at printing message only once for both direct and total effect.
> Ptint DAG result only once if identical

- DESCRIPTION
- R/check_dag.R
- R/check_heterogeneity_bias.R
- R/performance_aicc.R
- man/check_dag.Rd
- man/check_heterogeneity_bias.Rd
- tests/testthat/test-check_heterogeneity_bias.R
- tests/testthat/test-icc.R
- tests/testthat/test-r2.R
See https://github.com/glmmTMB/glmmTMB/pull/1102
> Update test based on glmmTMB fix

- DESCRIPTION
- NEWS.md
- R/check_model.R
- R/check_model_diagnostics.R
- R/check_normality.R
- R/check_outliers.R
- R/check_overdispersion.R
- man/check_model.Rd
- vignettes/check_model_practical.Rmd
- vignettes/simulate_residuals.Rmd
> Harnonize arguments

- DESCRIPTION
- NEWS.md
- R/check_outliers.R
- tests/testthat/test-check_outliers.R
> Check for influential observations of GLM w/o  numeric variables

- DESCRIPTION
- NEWS.md
- R/check_outliers.R
- man/check_outliers.Rd
I have a nice new dataset of a questionnaire validation that included attention checks. I have been playing with check_outliers(), and the OPTICS method. Interestingly, the current rule for its *threshold* that we have didn't work at all, + I had to change `xi`  to actually make it work (hence this PR that allows to do that).
Interestingly though, we typically consider outliers observations with a **large** distance, but my data shows that people that have failed  attention checks (i.e., "objective" outliers) tend  to have a low distance:
(the logistic model failed ~ distance_optics makes it a significant predictor of failure)
I wouldn't recommend any action for now, maybe we can simply mention this observation (that it is possible that low distances are also problematic) once my paper is …
> [Fix] check_outliers() expose 'xi' parameter for OPTICS

- DESCRIPTION
- R/check_collinearity.R
- man/check_collinearity.Rd
> check_collinearity() does not work with orthogonal polynomials

- DESCRIPTION
- NEWS.md
- R/check_collinearity.R
- tests/testthat/test-check_collinearity.R
- tests/testthat/test-check_model.R
> check_model() and other functions not working with only post-"hurdle" glmmTMB model

- DESCRIPTION
- NEWS.md
- R/r2_coxsnell.R
- R/r2_mcfadden.R
- R/r2_mckelvey.R
- R/r2_nagelkerke.R
- tests/testthat/test-check_singularity.R
- tests/testthat/test-r2_nagelkerke.R
> R2 incorrect for methods that use update(model, ~1) and have missing data

- DESCRIPTION
- R/check_group_variation.R
- R/zzz-deprecated-check_heterogeneity_bias.R
- man/check_group_variation.Rd
- man/check_heterogeneity_bias.Rd
- man/check_outliers.Rd
- tests/testthat/test-check_group_variation.R
@strengejacke we can keep working here, if you have more thoughts.
We can make two types of distinctions:
- Is variable X nested within groups (every group has a unique set of values of X)
- Is variable X crossed with groups (all groups have all possible values of X)
- (Or other)
But also:
- Does variable X vary between groups (is it correlated with group)
- Does variable X vary within groups
- (Or is correlated and varies within group)
So we have the following combinations (with "--" marking impossible situations):
|                | nested    | crossed  | other |
|----------------|-----------|----------|--------|
| **varies only between** | "between" | --       | "between"     |
| **varies only within**  | --  | "within" | --     |
| **both**           | "nested"        | --   | "both" …
> Revert nested change

- DESCRIPTION
- NEWS.md
> Prepare CRAN release
