- R/get_variance.R
- R/icc.R
- R/model_performance.bayesian.R
- R/r2.R
- R/r2_bayes.R
- R/r2_nakagawa.R
- man/r2_bayes.Rd
- Make sure `r2_bayes()` returns only one value, not the posterior
- add function that returns the posterior, for summary-function
> Minor revisions for r2()

- R/check_outlier.R
new test to check for influential observations via cook's distance
> adding `check_outlier`

- DESCRIPTION
@gjo11 Can you please provide us your name? 
We would like to include your name as a reviewer for this software, but we cannot figure out these details based on your GitHub profile. Thanks.
> add JOSS reviewers

- vignettes/r2.Rmd
Hello,
Thanks for this great package. 
Please find a typo corrected in the vignette.
> Typo in vignette

- R/check_normality.R
- R/compare_performance.R
- R/helpers.R
- R/icc.R
- R/performance_roc.R
https://github.com/easystats/easystats/issues/220
> use insight helpers

- DESCRIPTION
- R/check_distribution.R
- R/helpers.R
- R/performance_rmse.R
- R/performance_score.R
- R/r2.R
- R/r2_efron.R
- R/residuals.R
> use `convert_data_to_numeric()`

- .github/workflows/R-check.yaml
- .github/workflows/pkgdown.yml
- .github/workflows/test-coverage.yaml
https://github.com/easystats/easystats/issues/200
> Update to v2 of GHA

- tests/testthat/test-model_performance.lm.R
Should help to prevent regressions like one discussed in #449.
> Add test for factor response

- .github/workflows/render-readme.yml
- DESCRIPTION
- R/check_distribution.R
- R/helpers.R
- R/performance_rmse.R
- R/performance_score.R
- R/r2.R
- R/r2_efron.R
- R/residuals.R
@strengejacke This PR broke _performance_, but I am fixing it here.
So, once I updated _datawizard_ on CRAN, you will also need to update _correlation_ (https://github.com/easystats/easystats/issues/256).
> Fix breakage caused by datawizard

- NEWS.md
- R/check_outliers.R
> fixes #476

- R/check_outliers.R
- R/icc.R
- R/r2_nakagawa.R
- man/check_outliers.Rd
- man/icc.Rd
- man/r2_nakagawa.Rd
I want to add a paragraph on the difference between ICC and R2, because that's a question that keeps coming back. But unfortunately, I can't find anything concrete...
> [Docs] minor ICC docs improvement

- DESCRIPTION
- NEWS.md
- R/icc.R
- R/print-methods.R
- R/r2.R
- R/r2_nakagawa.R
- man/icc.Rd
- man/r2_nakagawa.Rd
- tests/testthat/test-icc.R
- tests/testthat/test-r2_nakagawa.R
> CI for mixed models R2 and ICC

- DESCRIPTION
- NEWS.md
- R/r2.R
- man/r2.Rd
> CIs for R2? - polish docs

- R/icc.R
- R/print-methods.R
- R/r2_nakagawa.R
- tests/testthat/test-icc.R
- tests/testthat/test-r2_nakagawa.R
> use bootMer

- R/check_outliers.R
- tests/testthat/test-check_outliers.R
First attempt at writing tests for easystats so welcome any feedback. I removed the `if (requiet("testthat") && requiet("performance"))` at the beginning since we discussed it wasn't necessary earlier since performance will already be installed and testthat as well.
> Add tests for check_outliers

- NEWS.md
- R/check_itemscale.R
- R/check_outliers.R
- R/item_difficulty.R
- man/compare_performance.Rd
- man/item_difficulty.Rd
- tests/testthat/test-item_difficulty.R
> issue with item_difficulty()-function

- R/check_collinearity.R
- tests/testthat/_snaps/check_collinearity.md
- tests/testthat/test-check_collinearity.R
> Make sure `ci=NULL` does not fail

- DESCRIPTION
- NEWS.md
- R/check_collinearity.R
- R/check_homogeneity.R
- R/check_outliers.R
- R/model_performance.bayesian.R
- R/model_performance.bife.R
- R/model_performance.lm.R
- R/performance_score.R
- tests/testthat/test-check_collinearity.R
- tests/testthat/test-icc.R
> Should model_performance() produce warnings when some measures can't be computed?

- R/check_homogeneity.R
- tests/testthat/test-check_normality.R
- tests/testthat/test-check_zeroinflation.R
- tests/testthat/test-rmse.R
> Suppress messages in tests

- R/check_normality.R
> Typo in message of `check_normality`

- DESCRIPTION
- NEWS.md
- R/check_predictions.R
- man/check_predictions.Rd
> check_predictions() produce empty plot

- DESCRIPTION
- NEWS.md
- R/performance_accuracy.R
- inst/WORDLIST
- man/performance_accuracy.Rd
- tests/testthat/test-performance_auc.R
> Supporting CIs for AUC #211

- DESCRIPTION
- R/check_model.R
- R/check_normality.R
- man/check_model.Rd
- man/check_normality.Rd
See https://github.com/easystats/see/pull/299
Also change default to `verbose = FALSE`
> Update check_model() defaults to align with see changes

- tests/testthat/test-check_outliers.R
Test `check_outliers` ics which on R devel re #607
> Fix `check_outliers` ics which test on R devel

- R/helpers.R
- R/r2_nakagawa.R
> Explained Variance for random slopes model

- DESCRIPTION
- NEWS.md
- R/r2_bayes.R
- man/icc.Rd
- man/r2_bayes.Rd
- man/r2_nakagawa.Rd
- tests/testthat/test-r2_bayes.R
> Marginal R2 is a misnomer in brms

- DESCRIPTION
- NEWS.md
- R/check_model_diagnostics.R
- tests/testthat/test-check_collinearity.R
- tests/testthat/test-check_convergence.R
- tests/testthat/test-check_model.R
- tests/testthat/test-check_normality.R
- tests/testthat/test-check_overdispersion.R
- tests/testthat/test-check_predictions.R
- tests/testthat/test-check_singularity.R
- tests/testthat/test-check_zeroinflation.R
- tests/testthat/test-r2.R
See https://github.com/glmmTMB/glmmTMB/issues/1101
> Fix failing glmmTMB tests

- DESCRIPTION
- NEWS.md
- R/check_singularity.R
- inst/WORDLIST
- man/check_singularity.Rd
- tests/testthat/test-check_singularity.R
> improved check_singularity

- DESCRIPTION
- NEWS.md
- R/check_predictions.R
- tests/testthat/test-check_predictions.R
> Specifying binomial data as proportion for `glmmTMB` confuses `check_predictions()`, consider weights
